
[window]
opacity = 1.0
# blur = true
[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
# family = "MesloLGS NF Mono"
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
# family = "MesloLGS NF Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#d6acff"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"

[colors.cursor]
text   = "#44475a"
cursor = "#f8f8f2"

[colors.selection]
text       = "#f8f8f2"
background = "#44475a"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "u"
mods = "Alt"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "m"
mods = "Alt"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "k"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "j"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "u"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "m"
mods = "Control|Shift"
