add_newline = false
format = '$directory$git_branch$git_status$character'
right_format = '$status$python$username$hostname'

[character]
vimcmd_symbol = '[](bold cyan)'

[status]
disabled = false
format = '[$status]($style)'

[directory]
style = 'bold purple'
read_only = ''

[git_branch]
format = '[$branch]($style) '
symbol = ''
style = 'bold green'

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'yellow'
deleted = 'x'

[username]
format = '[$user](yellow)'

[hostname]
format = '[@$hostname](green)'

[python]
format = '[$symbol$version](bold yellow) '
detect_extensions = []

[package]
disabled = true
